name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: uname -a
      
    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'

    - name: Build
      run: dotnet build

    - name: run
      run: dotnet bin/Debug/netcoreapp3.0/didactic-fortnight.dll
